server:
  port: 8673
  jwt.secret: Crayon

spring:
  cloud:
    gateway:
      routes:

      # login url
      - id: auth-login
        uri: lb://auth-server/login
        predicates:
          - Path=/login/**
          
      - id: user-regist
        uri: lb://app-web/user
        predicates:
          - Path=/user/**

      # app web layer
      - id: app-web
        uri: lb://app-web
        predicates:
          - Path=/app/**
        filters:
          - StripPrefix=1
          - JWTFilter=RSA256,HS256
          - RemoveResponseHeader=X-Powered-By
      # admin web layer
      - id: admin-web
        uri: lb://admin-web
        predicates:
          - Path=/admin/**
        filters:
          - StripPrefix=1
          - JWTFilter=RSA256,HS256
          - RemoveResponseHeader=X-Powered-By

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
