server:
  port: 8674
spring:
  application:
    name: auth-server
  redis:
    host: 127.0.0.1
    port: 6379
#   password:
    jedis:
      pool:
        max-active: 5
        max-idle: 5
        time-between-eviction-runs: 300
    
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
